sudo: required
language: c
compiler: gcc

notifications:
  email: false

jobs:
  include:
    - stage: build
      os: linux
      services: docker
      script: ./build.sh
    - stage: build
      os: osx
      script: ./build.sh
